// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA60FiOn1a9SM0O2kllE8-jnV_SA0BIquk',
    appId: '1:323578899153:web:c10acd4425a808c1ec33f0',
    messagingSenderId: '323578899153',
    projectId: 'chat-82d5d',
    authDomain: 'chat-82d5d.firebaseapp.com',
    storageBucket: 'chat-82d5d.appspot.com',
    measurementId: 'G-PDFN4Y3GR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-_QcMGlgtBSjdimHWNqAi4ZnYslITwjM',
    appId: '1:323578899153:android:578cd884f2024a28ec33f0',
    messagingSenderId: '323578899153',
    projectId: 'chat-82d5d',
    storageBucket: 'chat-82d5d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI4YRlU61h_VrDGj1CkqNaZ1P4dxc7B6s',
    appId: '1:323578899153:ios:e2f2ae58d9e6abb6ec33f0',
    messagingSenderId: '323578899153',
    projectId: 'chat-82d5d',
    storageBucket: 'chat-82d5d.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI4YRlU61h_VrDGj1CkqNaZ1P4dxc7B6s',
    appId: '1:323578899153:ios:c77fb19c53094b0aec33f0',
    messagingSenderId: '323578899153',
    projectId: 'chat-82d5d',
    storageBucket: 'chat-82d5d.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
